### ISSUE TITLE
Binary built from source using mux is not static 

### ISSUE THREAD

**Issue by aaronjwood** [gorilla/mux#105]
The binary that I get from building my program show's that shared libraries are in use:

linux-vdso.so.1 =>  (0x00007fff835e9000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5ae6201000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5ae5e3c000)
/lib64/ld-linux-x86-64.so.2 (0x00007f5ae642a000)

While this may not be a problem for most people it is for what I'm doing. Is this behavior intentional? Which piece of mux is causing this?

Thanks!

**Comment by kisielk** [comment]
This doesn't have anything to do with mux in particular. I believe on Linux if you import the "net" library it links to libc in order to use the DNS resolver.

You can rebuild your Go standard library with the `-tags netgo` and then rebuild your program with the same if you want to use the pure Go resolver.

**Comment by aaronjwood** [comment]
Sorry, my mistake. Thanks for the explanation!
