### ISSUE TITLE
404 with http.FileServer (only wiht gorilla mux)

### ISSUE THREAD

**Issue by elico** [gorilla/mux#137]
When I am using the next code:
router := mux.NewRouter().StrictSlash(true)
router.Handle("/ui/", http.StripPrefix("/ui/", http.FileServer(http.Dir("/tmp/ui/"))))

The result is that it only show the list of files in the directory.
So I have struggled and tried to understand what am I doing wrong?
What I eventually came up with was the next code which works:
router := mux.NewRouter().StrictSlash(true)
router.PathPrefix("/ui/").Handler(http.StripPrefix("/ui/", http.FileServer(http.Dir("/tmp/ui/))))

But I am unsure what exactly causing the issue? I have not tried to understand why it's like that in the library source code. So if somebody knows the answer please do.
And I am placing it here so maybe others who will have this issue will have some luck in their search using this post.

**Comment by elithrar** [comment]
Hi @elico - what path are you trying to access below `/ui/` - i.e. what is the full URL you're attempting to access? Something like `http://localhost:8000/ui/style.css`?

**Comment by elico** [comment]
Hi @elithrar - I have tried accessing both the root ie "/ui/" and some sub-directories and files ie "/ui/1.txt" or "/ui/ui/1.txt" which is like your example.
The only url which worked with the http.FileServer.. was the "/ui/" which returned the directory files listing(which I wanted also) all other files or folders returns a 404.

**Comment by elithrar** [comment]
Sorry for the delay (forgot about this one!) — but the reason `router.PathPrefix("/ui/").Handler(http.StripPrefix("/ui/", http.FileServer(http.Dir("/tmp/ui/))))` works is because `PathPrefix("/ui/")` means "/ui/*" (wildcard) - *anything* under `/ui/` should be handled here.

Simply putting `router.Handle("/ui")` doesn't work, as whilst that matches `http://domain.com/ui/` it does *not* match `http://domain.com/ui/style.css` as the path component is now `/ui/style.css` and not `/ui/` (i.e. not a match).

Some other routing libraries use a wildcard syntax instead, to the same effect.
