### ISSUE TITLE
StrictSlash is confusing

### ISSUE THREAD

**Issue by dobegor** [gorilla/mux#145]
This

"When true, if the route path is "/path/", accessing "/path" will redirect to the former and vice versa. In other words, your application will always see the path as specified in the route."

and

"When false, if the route path is "/path", accessing "/path/" will not match this route and vice versa."

should be inverted, because strict==true should mean no trailing slash allowed.
It's name and docs are confusing.

**Comment by dobegor** [comment]
There is also another problem with this setting.
If I define my path like 
```
r.Methods("POST").Path("/users/")
```
(note the trailing slash) this setting won't work at all. Either it should be fixed or mentioned in the docs.

**Comment by elithrar** [comment]
Thanks for the report. I won't have a chance to address this any time soon,
but am open to documentation PRs.

**Comment by dobegor** [comment]
@elithrar 
ok, I can fix it a bit later.
p.s.
sorry, does it work at all with POST methods?
here are details [link](https://groups.google.com/forum/#!topic/gorilla-web/exdHdVKGucM)

**Comment by dobegor** [comment]
@elithrar sorry, I can't test if this setting works with POST methods at all or I am doing something wrong (doesn't work for me, it just ignores this setting). That's why this needs some additional testing, because it can be related not only to documentation. Can't figure out reason myself.

**Comment by timjacobi** [comment]
I agree it is confusing. Express calls it strict routing which make more sense.
http://expressjs.com/en/api.html#express.router

**Comment by viktorbenei** [comment]
Just a note: if you'd change this I'd suggest you to opt for a different name, to not to silently break existing codes which depend on how this flag works today.

**Comment by Eksapsy** [comment]
I encountered on my first days of my interaction with the mux library. And I found this strange.
Why not make the `non-strict-slash` a non-default one? I don't think people who use the API really expect that kind of behavior and separation between `/v1/users/` and `/v1/users`. It's practically the same thing.

And it gets stranger, when you see that this works
```go
r := mux.NewRouter()
r.HandleRoute("/", ...)
```
But this doesn't
```go
s := r.PathPrefix("/users").Subrouter()
s.HandleRoute("/", ...) // Should return the same thing on `/users` and `/`
```
Or maybe that's just me?

**Comment by galvanidev** [comment]
> Eu encontrei esse comportamento nos meus primeiros dias de interação com a biblioteca de mux. E eu achei isso estranho. 
> Por que não fazer `non-strict-slash`um não-padrão? Não acho que as pessoas que usam a API realmente esperem esse tipo de comportamento e separação entre `/v1/users/`e `/v1/users`. É praticamente a mesma coisa.
> 
> E fica mais estranho e inconsistente, quando você vê que isso funciona
> 
> ```go
> r  : = mux. NewRouter ()
> r. HandleRoute ( " / " , ...) // Redireciona de `localhost: port /` para `localhost: port`
> ```
> 
> Mas isso não
> 
> ```go
> s  : = r. PathPrefix ( " / users " ). Subrouter ()
> s. HandleRoute ( " / " , ...) // Deve retornar a mesma coisa em `/ users` e` / `
> ```
> 
> Ou talvez seja só eu?

Happened to me too

**Comment by galvanidev** [comment]
> I encountered this behavior on my first days of my interaction with the mux library. And I found this strange.
> Why not make the `non-strict-slash` a non-default one? I don't think people who use the API really expect that kind of behavior and separation between `/v1/users/` and `/v1/users`. It's practically the same thing.
> 
> And it gets weirder and inconsistent, when you see that this works
> 
> ```go
> r := mux.NewRouter()
> r.HandleRoute("/", ...) // Redirects from `localhost:port/` to `localhost:port`
> ```
> 
> But this doesn't
> 
> ```go
> s := r.PathPrefix("/users").Subrouter()
> s.HandleRoute("/", ...) // Should return the same thing on `/users` and `/`
> ```
> 
> Or maybe that's just me?

Happened to me too

**Comment by Sirex2003** [comment]
For me too. And using StrictSlash(true) redirects my POST requests to GET:

```
router := mux.NewRouter().StrictSlash(true)
	router.Use(middleware.Authentication)
	router.Use(middleware.RequestLog)

subrouter := router.PathPrefix("/events").Subrouter()
subrouter.HandleFunc("/", exampleFunc).Methods(http.MethodGet, http.MethodPost)
```

**Comment by elithrar** [comment]
See the docs for StrictSlash -
https://godoc.org/github.com/gorilla/mux#Router.StrictSlash

A HTTP POST that receives a 301/302 response will followed by a GET as per
HTTP standards.

**Comment by liuxh0** [comment]
I also find it confusing.

I understand `StrictSlach` as *strictly* matching trailing slash as defined. Are there any reasons why it is reversed?

**Comment by alvanrahimli** [comment]
It is indeed very confusing, as I just wasted at least 5 hours debugging this. Guess what? A simple trailing slash is mandatory.
Why it is this way?

**Comment by NolPixel** [comment]
It's still bug?

I set StrictSlash true,,,
`r.HandleFunc("/path/", pathHandler)`

And try on Incognito mode direct access to 127.0.0.1/path

Expected redirect to /path/ reality ended with 404 not found.

**Comment by crisscross82** [comment]
## aidev status

**⏸ Awaiting human decision**

Critic recommends: kill

_Updated 2026-04-15T06:40:34Z_

**Comment by crisscross82** [comment]
<details><summary><strong>Scout brief</strong> <sub>(aidev, 2026-04-15T06:28:13Z)</sub></summary>

## Purpose
The `gorilla/mux` repository is a Go package for HTTP request routing and dispatching. It allows developers to define routes based on URL patterns, methods, headers, and more, and maps incoming requests to the appropriate handler functions.

## Architecture
- **Packages**: 
  - `mux`: Contains the core router implementation.
  - `middleware`: Provides middleware functions for handling common tasks like CORS, authentication, etc.
  - `test_helpers`: Includes utility functions for testing routes and handlers.

## Stated Principles
- Routes can be matched based on URL host, path, path prefix, schemes, header and query values, HTTP methods or using custom matchers.
- URL hosts, paths, and query values can have variables with an optional regular expression.
- Registered URLs can be built, or "reversed", which helps maintain references to resources.
- Routes can be used as subrouters for organizing routes that share common conditions.

## Unknowns
- What specific features or improvements are being considered for this repository?
- Are there any dependencies or external libraries that need to be accounted for in the development process?
- How should the middleware and testing utilities be extended or modified?

</details>

**Comment by crisscross82** [comment]
<details><summary><strong>Critic report</strong> <sub>(aidev, 2026-04-15T06:28:56Z)</sub></summary>

**Proposal:** Rename or invert the semantics of `StrictSlash` in gorilla/mux because "strict" intuitively suggests "no trailing slash allowed," but the current behavior when `true` redirects between slash/no-slash variants instead.

---

## Arguments FOR

- **Principle of Least Surprise:** The name `StrictSlash` with `true` naturally reads as "be strict about slashes" (i.e., reject mismatches), but it actually does the opposite — it redirects to normalize. This is a genuine usability issue that has confused users.
- **Advances the product's stated purpose:** gorilla/mux exists to route HTTP requests. A confusing core API option undermines the routing experience and leads to subtle bugs (unexpected 301 redirects instead of 404s).
- **Documentation alone hasn't solved it:** The fact that this issue was filed despite existing documentation suggests the naming is inherently misleading — better docs won't fix a bad name.
- **Real-world impact:** Unexpected 301 redirects can break POST/PUT requests (method gets changed to GET on redirect in many clients), causing data loss or silent failures.

## Arguments AGAINST

- **Reversibility (one-way door):** Renaming or inverting `StrictSlash` is a public API break in a widely-used package. This is a one-way-door decision with massive blast radius — every consumer using `StrictSlash(true)` would break silently if semantics are inverted, or loudly if renamed. The Reversibility principle demands a louder justification and rollback plan, and there is none here.
- **YAGNI / Should this exist?:** The feature works correctly; the complaint is about naming. Renaming a public API symbol to satisfy a naming preference is high cost for marginal gain. Users who read the docs once learn the behavior permanently.
- **Cheaper alternative exists:** A documentation improvement (adding examples, a "Common Gotcha" note, or a one-line clarification like "StrictSlash normalizes slashes via redirect, it does not reject mismatches") solves 90% of the confusion at zero breaking-change cost.
- **gorilla/mux is in maintenance mode:** The project has been largely archived/low-activity. Introducing a breaking API change in a stable, widely-depended-upon package is disproportionate to the benefit.
- **Scope creep risk:** If the team inverts semantics, they also need to audit all internal uses, update all examples, handle migration guides, and potentially maintain both APIs during a deprecation period.

---

## Sharp Questions

1. **Is gorilla/mux still accepting breaking API changes?** If the project is archived or in maintenance-only mode, this is dead on arrival regardless of merit.
2. **What is the actual user harm beyond initial confusion?** Are there reported bugs where `StrictSlash` caused production incidents, or is this purely a readability complaint that resolves after reading the docs once?
3. **Would you accept a docs-only fix instead?** A better godoc comment with an explicit example showing the redirect behavior could resolve the confusion without any API break.

---

RECOMMENDATION: kill

The naming is genuinely confusing, but this is a public API in a stable, widely-used package. Inverting or renaming it is a breaking change with massive downstream impact, and the confusion is fully addressable with a documentation improvement. The cost/benefit ratio is upside-down.

</details>

**Comment by crisscross82** [comment]
<details><summary><strong>Scout brief</strong> <sub>(aidev, 2026-04-15T06:39:45Z)</sub></summary>

## Purpose
The `gorilla/mux` repository is a popular HTTP request router and dispatcher for Go applications, providing features such as URL routing with variable extraction, support for custom matchers, middleware handling, and graceful shutdown.

## Architecture
- **Packages**: 
  - `mux`: Contains the core routing logic.
  - `middleware`: Houses middleware implementations.
  - `test_helpers`: Provides utility functions for testing routes and handlers.
- **Files**:
  - `mux.go`: Main router implementation.
  - `middleware.go`: Middleware handling logic.
  - `route.go`: Route definition and matching logic.

## Stated Principles
- The router should be compatible with the standard `http.ServeMux`.
- Routes can be matched based on URL host, path, path prefix, schemes, header, query values, HTTP methods, or custom matchers.
- Registered URLs can be built (reversed), which helps maintain references to resources.
- Routes can be used as subrouters for grouping common conditions.

## Unknowns
- What specific features or improvements are being considered for the repository?
- Are there any dependencies or external libraries that need to be accounted for in the evaluation?

</details>

**Comment by crisscross82** [comment]
<details><summary><strong>Critic report</strong> <sub>(aidev, 2026-04-15T06:40:33Z)</sub></summary>

**Proposal:** Rename or invert the semantics of `StrictSlash` in gorilla/mux because the current name implies "strict = no trailing slash allowed," but the actual behavior is the opposite (strict = redirect to canonical form).

---

## Arguments FOR

- **User confusion is real.** The name `StrictSlash` naturally reads as "be strict about slashes" (i.e., reject mismatches), but it actually means "be lenient and redirect." This is a genuine usability issue for a router library whose purpose is clear, predictable URL matching.
- **Aligns with stated purpose.** gorilla/mux aims to be a straightforward, powerful router. A confusingly-named core API option undermines that goal — users must read docs carefully to avoid subtle routing bugs.
- **Documentation alone hasn't fixed it.** The issue exists despite the behavior being documented, suggesting the name itself is the root cause of confusion.
- **Small surface area.** `StrictSlash` is a single boolean option on the router — the conceptual change is narrow.

---

## Arguments AGAINST

- **Reversibility (one-way door).** This is a public API on one of Go's most widely-used routers. Renaming it or inverting its semantics is a breaking change that affects every consumer. There is no feature flag or gradual migration — it breaks at compile time (rename) or silently at runtime (semantic inversion). This violates the **Reversibility** principle hard.
- **YAGNI / Should this exist?** The current behavior *works correctly*. The issue is about naming, not functionality. Users who read the docs get the right behavior. A breaking change to fix a naming preference is disproportionate cost for the benefit.
- **Cheaper alternative exists.** Better documentation, a code comment, or a new *additive* option (e.g., `RedirectSlash`) that's better-named could coexist alongside the existing API without breaking anyone. The repo could deprecate `StrictSlash` over a long cycle.
- **Scope creep risk.** If the team inverts semantics, every tutorial, blog post, Stack Overflow answer, and downstream project referencing `StrictSlash(true)` becomes wrong. The blast radius extends far beyond the repo.
- **gorilla/mux is in maintenance mode.** The project has been largely stable/archived. Introducing a breaking API change to a mature, widely-deployed library with minimal active development is high risk, low reward.

---

## Sharp Questions

1. **Is gorilla/mux planning a major version bump (v2)?** A breaking rename only makes sense during a major version transition. If not, this change cannot ship without violating semver.
2. **Has anyone measured how often this confusion causes actual bugs vs. momentary surprise?** If users figure it out after reading docs and never hit a runtime issue, the cost of a breaking change outweighs the benefit.
3. **Would an additive, better-named alternative (e.g., `RedirectTrailingSlash(bool)`) plus deprecation of `StrictSlash` satisfy the concern without breaking existing users?**

---

RECOMMENDATION: kill

The naming is admittedly unintuitive, but this is a public API on a widely-consumed, stable library. Inverting semantics is a silent runtime break; renaming is a compile-time break across the ecosystem. The fix (better docs or an additive alias with deprecation) doesn't require the proposed change. Breaking a mature API to fix a naming preference fails the Reversibility test decisively.

</details>
