### ISSUE TITLE
mux.Vars and schema.Decoder interoptability.

### ISSUE THREAD

**Issue by james-lawrence** [gorilla/mux#171]
would be nice is there was a way to get the results of mux.Vars (using a different function) in a format that schema.Decoder can understand.

**Comment by elithrar** [comment]
Can you share an example of what you would like this to look like and/or
what your use-case is?

**Comment by james-lawrence** [comment]
absolutely, excuse any blatant errors in the example, psuedo coding =)

```golang
func handler(w *http.ResponseWriter, req *http.Request) {
  type Msg struct {
      Field1 bool   `schema: 'field1'`
      Field2 string `schema: 'field2'`
  }
  var (
    msg Msg
  )
  _ =  req.ParseForm()
  _ = schema.NewDecoder.Decode(&msg, mux.Vars(req))
  _ = schema.NewDecoder.Decode(&msg, req.PostForm)
}
```

**Comment by themihai** [comment]
@james-lawrence but you do that anyway with the PostForm isn't it? You could use a middleware to copy mux.Vars to PostForm (so that you have to use only map PostForm) or even decode it directly using schema.Decode but what if the body is encoded differently(e.g. json or another format)? There are several magic(more or less) frameworks (e.g. martini) but I think it's really something that should be built on top of gorilla mux not part of it. All that magic has tradeoffs (i.e. performance, flexibility etc)

**Comment by james-lawrence** [comment]
I don't see how different encodings matter in this case? My point was an attempt to make it a little more accessible using off the shelf tools, All it really needs is a method to return url.Values instead of a map[string]string.

this is hardly 'magic' its just a convience. yes there is a performance tradeoff but you can still map manually if you want/need to. 

Anyways this was more just a question of if there was anyone else who felt it was kludgey.

**Comment by elithrar** [comment]
Unlikely to implement this directly in mux, but open to a documentation PR for mux.Vars -> r.PostForm.
