### ISSUE TITLE
Merging PR #169 breaks existing code

### ISSUE THREAD

**Issue by nwidger** [gorilla/mux#182]
This change seems to have the very unfortunate side effect of breaking code that stores any request context data keyed by a request's address (such as gorilla/context).  I have code that sets a value using gorilla/context.Set, routes the request with gorilla/mux and then expects to be able to retrieve that value in my handlers with gorilla/context.Get.  With this change, the call to Get returns nil because the request address changed when setVars/setCurrentRoute is called in Router.ServeHTTP.  I'm assuming it should be possible to use gorilla/mux in combination with gorilla/context, so this seems like an issue to me.

**Comment by elithrar** [comment]
@nwidger Can you share your code so I can get a better understanding how you are using context + mux today? Go 1.6?

**Comment by nwidger** [comment]
I can provide a more detailed example but hopefully this demonstrates how I was using context+mux in the past: https://play.golang.org/p/LoejXfXWtu

This was working previously with Go 1.6 as well as many previous versions.

**Comment by elithrar** [comment]
@nwidger So you're using Go 1.7 rc3? (it's not clear: the behaviour should not have changed at all, but especially for Go 1.6, where the implementation never changed at all).

**Comment by nwidger** [comment]
Here's a runnable example that shows the problem:

https://play.golang.org/p/KHn9Fcv-ZN

Run it and navigate to http://localhost.  If built with Go 1.6.3 it prints "bob" to the screen.  If built with Go 1.7 rc6 it prints "no context stored for request".

Hopefully that highlights the issue better, I apologize if my original bug report wasn't clear.

**Comment by elithrar** [comment]
No problems - thanks for the runnable example. I'll take a look when I get
home tonight!

**Comment by elithrar** [comment]
OK, so this happens because `r.WithContext()` in Go 1.7, which gorilla/mux uses in Go 1.7, creates a shallow copy of the request: https://github.com/golang/go/blob/master/src/net/http/request.go#L288-L298

This shallow copy, as you'd expect, changes the address of the request in gorilla/context's `map[*http.Request]map...`, effectively islanding any context values.

This is a shortcoming in gorilla/context: *any* library, mux included, will break it come Go 1.7 and the `http.Request.WithContext()` method.`

I'm not sure if there's a clean way to fix this: one option would be to call `context.GetAll` to copy all values from the old request before we call `WithContext`, and then save them back into the (shallow) copy, but if you have private types as keys (which is recommended), then we can't reliably achieve that. It would also add `context` back as a dependency to mux.

The short answer here, which involves some pain up-front: move off gorilla/mux. Write a shim like we have in [`context_native.go`](https://github.com/gorilla/mux/blob/master/context_native.go) and [`context_gorilla.go`](https://github.com/gorilla/mux/blob/master/context_gorilla.go) to abstract this across versions.

I hope this helps. The breaking change was hard to anticipate here and was not intended, but was ultimately unavoidable. *Any* package that mixes gorilla/context and `http.Request.WithContext()` will run into this.

**Comment by kisielk** [comment]
This is an unfortunate breakage. However I also feel like gorilla/context has outlived it's purpose now that context will be in the stdlib. It's a much better way to manage per-request state and will probably also interact better with the new per-goroutine GC stuff that will be making its way in.

It may be extreme, but maybe in the interest of backwards compatibility we should put go1.7 context behind a build tag for now?

**Comment by nwidger** [comment]
@elithar For my own situation, I've already bypassed this issue by replacing gorilla/context with the new context package, similar to what you suggested.  So this isn't an issue for me anymore, but it may be for others which is why I reported it.

**Comment by elithrar** [comment]
> It may be extreme, but maybe in the interest of backwards compatibility we should put go1.7 context behind a build tag (other than go1.7) for now?

I'm more concerned that, even with a build tag (e.g. `+newcontext`) that *anyone* using gorilla/context *and* request.WithContext() (even indirectly via a library) will run into this issue. If gorilla/mux still relies on gorilla/context, then it would break `mux.Vars`.

It's definitely unfortunate, but I don't think it's actually fixable in a mixed-context environment.

**Comment by nwidger** [comment]
Technically, so long as you use gorilla/context.Set after all calls to request.WithContext() you shouldn't run into this issue.

**Comment by elithrar** [comment]
> Technically, so long as you use gorilla/context.Set after all calls to request.WithContext() you shouldn't run into this issue.

Correct, but this is the less-common use-case: most users are calling `Set` in middleware (and before routing), and then `Get` in their handlers - which is intractable.

**Comment by kisielk** [comment]
It seems like we should probably put a warning in the readme of gorilla/context that it's not compatible with using the new http context?

**Comment by elithrar** [comment]
Yep! Was going to do that tonight.

**Comment by marcosnils** [comment]
Just ran across this. Too bad I need to refactor my app to make this work :(

**Comment by PolyviosT** [comment]
Hello, 

It seems with Go 1.7 this tag you have under context_gorilla: // +build !go1.7 is breaking the vendoring of godeps as it is not including the context module. Any workarround?

**Comment by elithrar** [comment]
The pre-1.7 builds should include the old gorilla/context module. Are you
saying Godeps does not see this?

**Comment by PolyviosT** [comment]
Yes it seems Godeps don't see it, unless I am missing something.

**Comment by elithrar** [comment]
https://github.com/tools/godep/issues/367

Does anything there fix the issue? This sounds like a bug with godep as mux
isn't doing anything special here.

**Comment by elithrar** [comment]
Closing this out - see docs.

**Comment by plv1313** [comment]
I am not convinced that this is a godep bug. Godep by default is including all deps it finds regardless of tags (except for ignore and app engine). So as expected when Godep see this tag // +build !go1.7 will ignore it.
