### ISSUE TITLE
SetCookie value none doesn't delete cookie

### ISSUE THREAD

**Issue by prats226** [gorilla/mux#229]
I have an endpoint for logout which deletes cookie for current domain.
`
    deleteCookie := http.Cookie{Name: "Auth", Value: "none", Expires: time.Now()}
    http.SetCookie(w, &deleteCookie)
`

It works when called using HandleFunc method of default net/http. However when same Handler is called with default net/http ServeMux. However when called with gorilla mux router mux.NewRouter(). cookie doesn't get deleted.

With options  Value: "", MaxAge: -1, it works with gorilla mux

**Comment by elithrar** [comment]
Can you share a minimal example I can run?

**Comment by hueich** [comment]
To tell the client to delete the cookie, you should set the `Expires` value to sometime in the distant past, like the epoch, to get around clock skew between server and client.  Also, since cookie expiration value only has granularity in seconds, if the following http request comes within the same second, the client might still send the cookie.

**Comment by kisielk** [comment]
If there's actually a bug and you have a reproducible example please reopen.
