### ISSUE TITLE
no handler mapping of http  method

### ISSUE THREAD

**Issue by hellojukay** [gorilla/mux#275]
`outer.HandleFunc("/index", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hello"))
	}).Methods("POST")`

this code , i regist a url "/index",but when i access the url by get method,it return httpstatus is 404,i think it should return 405

**Comment by elithrar** [comment]
There's a semantic difference here: 404 means not found, which is
reflective of the route not existing for that method.

405 means method not allowed, which often has intent, and a router library
can't know that ahead of time.

You can always create middleware or modify Router.NotFoundHandler to return
405 instead of 404 for routes that exist.
