### ISSUE TITLE
Spoiling of query parameter with + inside

### ISSUE THREAD

**Issue by ceoworks** [gorilla/mux#276]
Hello, we faced a bug recently with following query: `?mime=image%2Fsvg%2Bxml`

If we log the whole request, it looks like `/check?mime=image/svg+xml`, and it's actually what we expect.

But when it comes to getting of this parameter as string in code with command `r.URL.Query().Get("mime")`, it then looks spoiled `image/svg xml` - we lost our `+` and get space instead 😢 

Any ideas where to look and how to fix?

**Comment by colonelmo** [comment]
The `+` to `[space]` transformation happens (as it should) [here](https://github.com/golang/go/blame/master/src/net/url/url.go#L245-L250) in `/net/url/url.go`.

Since the following piece of code is working as you would like

```Go
u, _ := url.Parse("/check?mime=image/svg%2Bxml")
println(u.Query().Get("mime")) // prints image/svg+xml
```

I guess you should also be getting the correct result  if you do something similar to a query which correctly escapes the plus character.

But if you're getting a query and you're sure about the parameters being escaped correctly, and you're still getting the incorrectly decoded string `image/svg xml`, I would blame any sort of  middleware which would intercept and somehow modify the request object (assuming you're using this in the context of an http server) for routing or logging purposes.

Could you peek at `r.URL.String()` right before you try to `.Get("mime")`?

Could you provide a full example which recreates this issue?

**Comment by kisielk** [comment]
If you're still having the problem please reopen with code for reproducing the bug.
