### ISSUE TITLE
Go1.8 on App Engine breaks Context

### ISSUE THREAD

**Issue by conradhappeliv** [gorilla/mux#291]
It seems that right now there's a bug in the development tooling for Google App Engine that causes build tags to not be sent to the compiler correctly. As Mux uses these tags to decide whether it should use the native Go Context or its homebrew Context, the correct one isn't being used, causing side effects such as this:

```
func(w http.ResponseWriter, r *http.Request) {
    log.Println(Mux.Vars(r)) // --> [yourVar: 12345]
    r = r.WithContext(context.WithValue(r.Context(), ContextKey{}, val))
    log.Println(Mux.Vars(r)) // --> [] Mux's Vars get destroyed :(
}
```

This seems to have been acknowledged by Google here: https://groups.google.com/d/msg/google-appengine-go/vj2_csObT-w/UVYDh6kSAQAJ

However, I wanted to post here because for one, I spent hours thinking it was something wrong with Mux and don't want people to have to repeat the process, and also because I wanted to suggest that maybe Gorilla should have an alternative, more explicit way to select the correct Context, rather than just relying on a magic feature.

**Comment by elithrar** [comment]
The challenge here is that the "magic"—using build tags—solves the case where `http.Request.Context` does not exist pre-Go 1.7. We still need to cover that case to support older versions of Go, and allowing users to swap between context versions adds complexity to the API — i.e. "why is there a choice? is one better?" — instead of having sane defaults.

I get that it's frustrating after debugging for several hours, but I don't think we should throw the baby out with the bathwater because of a GAE-specific regression.
