### ISSUE TITLE
Return the empty value in mux.Vars (r)

### ISSUE THREAD

**Issue by okabbas** [gorilla/mux#359]
**Go Version : 1.10
mux Version : 1.6.1**

Unfortunately, the mux does not work properly on my system and returns an empty amount. what's wrong ?

**main code :**
```Groovy
package main

import (
	"net/http"
	"runtime"
	"../app/auth"
	"github.com/gorilla/mux"
)

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU())
	initRouter()
}

func initRouter() {
	router := mux.NewRouter()
	router.HandleFunc("/user/register", auth.RegisterUser).Methods("POST")
	http.ListenAndServe(":9999", router)
}
```

**auth code :** 
```Groovy
package auth

import (
	"net/http"
	"github.com/gorilla/mux"
	"fmt"
)

func RegisterUser(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Vars: %v\n%v", mux.Vars(r), r.URL.Path)
}
```

I pass this Json value to the server with the **POST** method : 

> {
> 	"IsActive": true
> }

**output :** 

> Vars: map[] 
> /user/register

**Comment by elithrar** [comment]
* You don't have any route vars. `mux.Vars(r)` prints out the route parameters, not POST form values. You want `r.PostFormValue` (and related methods) for that - https://golang.org/pkg/net/http/#Request.PostFormValue
* You also don't need `runtime.GOMAXPROCS(runtime.NumCPU())` - Go will do this by default since ~1.5.
