### ISSUE TITLE
Convert tests to use subtests with t.Run

### ISSUE THREAD

**Issue by kisielk** [gorilla/mux#409]
Just a maintenance task, but it will make test reporting cleaner in case of failure:

https://blog.golang.org/subtests

**Comment by kanozec** [comment]
I think I can take this, but I'm not familiar with the go test. I just have some practice before.
Could you give me some advice for which test file to refactor first.
I think that would be really helpful, thx.

**Comment by kisielk** [comment]
Still valid

**Comment by fharding1** [comment]
I'm happy to take this on for the remainder of the tests. I assume you tagged this as still valid because like https://github.com/gorilla/mux/blob/ed099d42384823742bba0bf9a72b53b55c9e2e38/middleware_test.go#L48 and some other places similar to that could use subtests? Also, should I update `old_test.go`, or is that unmaintained (per comment `// Old tests ported to Go1. This is a mess. Want to drop it one day.`).

**Comment by fharding1** [comment]
Should this issue be closed? Seems like most every test that it makes sense for is using subtests now.
