### ISSUE TITLE
Which companies use gorilla/mux in production?

### ISSUE THREAD

**Issue by chughpiyush** [gorilla/mux#487]
Hi everyone!

I'm curious to know which companies are using gorilla/mux in production already. Any particular pros/cons that you noticed on your way to production...

If you use it in any of your products, please let me know. I would like to include a list of such companies in README.md, it can be inspiring for others to see which companies are already using gorilla/mux and it can help them get comfortable knowing about success from the others.

**Comment by elithrar** [comment]
Happy to include such a list in the README, but no need to cc everyone
directly - people will be notified if they follow the repo (please don’t @
people for issues like this!).

**Comment by zimmski** [comment]
Well, we at Symflower (https://symflower.com) are using gorilla/mux basically for every HTTP/HTTPS service. Since I am using this project now for years without any problems (besides some additional changes for unit testing, which we want to upstream anyway) I do not have any comparison to other projects since I am completely happy with it. So cons: it does exactly what we want, and does not get in our way. We have gorilla/mux vendored, so I haven't seen a lot of the latest commits. Will update with the next sprint. Maybe some con shows up ;-)

**Comment by rojakcoder** [comment]
@zimmski The "additional changes for unit testing" that you mentioned - what kind are those? Do they have anything to do with the [session info being lost due to Gorilla Sessions](https://github.com/gorilla/sessions/issues/80)? Anything related to [this set of changes](https://github.com/gorilla/sessions/commit/12bd4761fc66ac946e16fcc2a32b1e0b066f6177) in [PR #175](https://github.com/gorilla/sessions/pull/175)?
