### ISSUE TITLE
Reflected XSS All Clients in mux.go

### ISSUE THREAD

**Issue by kewilson** [gorilla/mux#511]
Our security scanning has reported a high risk vulnerability in the mux library, details below. Please let me know if there is any other information needed by your team to address this security issue. 

Also please provide a timeframe for when an expected fix will be released, thanks! 

Vulnerability Group | Go High Risk
Vulnerability Name | Reflected XSS All Clients
Severity | High
CWE ID | 79 | https://cwe.mitre.org/data/definitions/79.html
Language | Go
Full Path | vendor/github.com/gorilla/mux/mux.go

vendor/github.com/gorilla/mux/mux.go:137
   w.Header().Set("Location", p)
vendor/github.com/gorilla/mux/mux.go:135
   p = url.String()
vendor/github.com/gorilla/mux/mux.go:133
   url := *req.URL

**Comment by fharding1** [comment]
Hi @kewilson, while gorilla/mux should have a SECURITY.md outlining how to report vulnerabilities, please note that this is not a responsible way to disclose a security vulnerability that can affect thousands of projects using gorilla/mux. I've created an issue for that #512 

Could you attach a proof of concept for how this could be exploited in a meaningful way? I'm not sure I understand how this alone could be an issue. Since the cleaned path will always start with a slash, I don't think it could ever redirect to another origin or something like that. AFAICT the most you could do is cause the server to redirect the browser from something like `/foo//?url=bar` to `/foo?url=bar`, something like `//google.com` would just go to `/google.com`.

**Comment by elithrar** [comment]
This aligns with the below on the current HEAD:

https://github.com/gorilla/mux/blob/master/mux.go#L182-L191

**Comment by fharding1** [comment]
I believe `net/http.ServeMux` exhibits this same behavior.

**Comment by elithrar** [comment]
I don't see this as a reflected XSS attack, as the path is:

* Cleaned
* Only URLs accepted by the application - e.g. the router has to accept the host/URL first before reflecting it.
* As per https://github.com/gorilla -> please email gorilla-maintainers@googlegroups.com with a PoC if you believe this is an issue @kewilson - I appreciate the report, but echo the sentiment to reach out privately.

**Comment by kewilson** [comment]
Apologies for the security report ruffling some feathers, I'll be sure to look for a security.md. Well, as you say, if the commercial security scanner used is incorrect then I'll mark it as a false positive and we can all rest easy.

**Comment by elithrar** [comment]
No problems. Out of curiosity - what was the tool?

**Comment by jdelta-RBS** [comment]
@fharding1  No sure why you'd start by telling him it's irresponsible to report a vuln in that way (...despite you not having a security.md?!), then ask for a PoC to be posted that can exploit it.

**Comment by fharding1** [comment]
Responsible disclosure sometimes unfortunately means sometimes looking about a bit for a contact. Regardless of not having a security.md, gorilla does have contact info outside of GitHub that could have been used. 

And I didn't care too much if he posted a PoC here because this issue already exists, but yeah, I probably should have told him to email the gorilla email with a PoC.

**Comment by jdelta-RBS** [comment]
I think that is fair, but from the researcher's standpoint if you do not have a security.md, a public GitHub issue tracker is a responsible place to post an issue that is easily fixed (in this case, a false-positive XSS from a scanner).

**Comment by elithrar** [comment]
Not looking to cast blame on any individual here, but:

• there is a public email address on our GitHub org
• in lieu of that, an issue asking for a private contact / to report an
issue would have also been acceptable
• I’m going to lock this topic as I think the conversation has run its
course w.r.t. the mux project itself.
