### ISSUE TITLE
[question] unregistering a static content handler

### ISSUE THREAD

**Issue by maffeis** [gorilla/mux#523]
Greetings!

Is it possible to remove a static content handler registered with:

`r.PathPrefix("/static/").Handler(http.StripPrefix("/static/", http.FileServer(http.Dir(dir))))`

?

Silvano

**Comment by elithrar** [comment]
There is not a way to unregister a route. 

Would you mind expanding on your use-case more?

**Comment by maffeis** [comment]
Hi Matt. We have a use case whereby document roots can be mounted or unmounted to a host running a golang application. Those volumes contain static web content, and we would like to publish/unpublish those docroots dynamically.

**Comment by misterr8472** [comment]
Hi guys,

I have the same use-case. I'd like to dynamically serve static content (for example, a static site sitting in one directory or another). I would then like to un-register that route, because I don't want routes piling up (not sure when the number of routes becomes a problem? In my case we'd probably hit a million within a year). Additionally, it seems unsafe to have an http directory be served forever, even if it sits behind a UUID-based link (which is how we are securing things at the moment). 

I saw another discussion where you suggested swapping out the router entirely when this needs to be done (https://github.com/gorilla/mux/issues/82) but that seems like a pretty resource-intense thing to do possibly hundreds of times a day with any number of users connected?

**Comment by misterr8472** [comment]
Hi all,

looks like there has not been an update to this. Do any of you believe there are other ways around this?

Would it be possible, for example, to register a single route with a function that serves a different http directory based on some kind of ID passed into it? You could, perhaps, match a site's ID to a directory name and then that's the directory served up somehow. 

My problem is that I have to use a subrouter (these are publicly viewable links outside of the middlewares used for my server) with an http.FileServer, like so:

previewserver.PathPrefix(pathprefix).Handler(http.StripPrefix(pathprefix, http.FileServer(http.Dir(previewDir))))

where previewserver is the subrouter I have created and the pathprefix is using an ID I randomly generate. This is all happening within a HandleFunc I have already registered with the main router.

Could a fileserver be launched within an existing HandleFunc without having to register a new route or subrouter?

**Comment by misterr8472** [comment]
Hi all,

assuming you had a few directories with a static site in each. If you had users who get access to only a specific directory (ideally via a new secure link generated each time), how would you prevent those 'secure' links from 'piling up' in the form of more and more routes being added to the router?
