### ISSUE TITLE
Registering route while running

### ISSUE THREAD

**Issue by ski7777** [gorilla/mux#524]
Hello,

I´m trying to add a route after the server is already running.

```
type WSServer struct {
	server   *http.Server
	router   *mux.Router
}

type WSServerConfig struct {
	HTTPServerConfig
}

func NewWSServer(config *WSServerConfig) *WSServer {
	s := new(WSServer)
	s.router = mux.NewRouter()
	webbox := packr.New("web", "../../../web")
	staticbox := packr.New("web/static", "../../../web/static")
	registerStaticFile(s.router, webbox, "index.html")
	s.router.PathPrefix("/static/").Handler(http.StripPrefix("/static/", http.FileServer(staticbox)))
	s.router.HandleFunc("/api/v1/sendmsg", s.apihandler("sendmsg")).Methods("POST")
	s.router.HandleFunc("/api/v1/registerclient", s.apihandler("registerclient")).Methods("POST")
	s.router.HandleFunc("/api/v1/login", s.apihandler("login")).Methods("POST")
	s.router.HandleFunc("/api/v1/clients", s.apihandler("clients")).Methods("POST")
	s.router.NotFoundHandler = s.router.NewRoute().HandlerFunc(notfound).GetHandler()
	s.server = &http.Server{
		Addr:         config.GetAddr(),
		WriteTimeout: time.Second * 15,
		ReadTimeout:  time.Second * 15,
		IdleTimeout:  time.Second * 60,
		Handler:      s.router,
	}
	s.upgrader = new(websocket.Upgrader)
	return s
}

// Start stars the server
func (ws *WSServer) Start() error {
	return ws.server.ListenAndServe()
}

func (ws *WSServer) RegisterLater() {
	ws.router.HandleFunc("abc", func(http.ResponseWriter, *http.Request){}).Methods("GET")
	ws.router.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
		t, err := route.GetPathTemplate()
		if err != nil {
			return err
		}
		fmt.Println(t)
		return nil
	})
}

func main(){
	s := NewWSServer(someconfig)
	s.Start()
	s.RegisterLater()
}
```

The output won´t show the `abc` route and `GET /abc` will end up in 404.

Can someone help me fixing this problem?

Regards
Raphael

**Comment by fharding1** [comment]
> I'm trying to add a route after the server is already running.

Could you expand on your use case a bit more? This seems like an uncommon thing to do.

> Can someone help me fixing this problem?

Of course! In the future, it might be better if you could provide a runnable minimal reproduction of the issue you're having (the code snippet you posted does not run). This will allow people to focus on the issue you're having, rather than anything else in your code. Here is an example:

```go
package main

import (
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()

	router.HandleFunc("/", func(res http.ResponseWriter, _ *http.Request) {
		io.WriteString(res, "Hello!")
	})

	go func() {
		time.Sleep(time.Second * 5)

		router.HandleFunc("/asdf", func(res http.ResponseWriter, _ *http.Request) {
			io.WriteString(res, "Hello from the handler registered later!")
		})

		fmt.Println("registered second handler!")
	}()

	http.ListenAndServe(":8080", router)
}
```

As you can see from running this example, it's totally possible to register a handler after starting a server pointing at the router you've using. I would guess the reason it isn't working for you is because of this:

`ws.router.HandleFunc("abc", func(http.ResponseWriter, *http.Request){}).Methods("GET")`

You're registering route `abc`, when I think you should be registering `/abc`.

**Comment by ski7777** [comment]
Hello,

Thanks for your answer.

Here is the not-working: https://github.com/ski7777/gomultiwa/blob/master/internal/webserver/websocketserver/websocket.go#L69&L99
If I would put a printout right before line 71 it would print `<nil>´. You may test this code by applying this:
```
diff --git a/internal/gomultiwa/gomultiwa.go b/internal/gomultiwa/gomultiwa.go
index 18b7cbb..9b75330 100644
--- a/internal/gomultiwa/gomultiwa.go
+++ b/internal/gomultiwa/gomultiwa.go
@@ -55,6 +55,9 @@ func (g *GoMultiWA) Start() {
                        log.Fatal(err)
                }
        }()
+       go func() {
+               g.ws.HandleExtensionFunc("GET", "/abcdefg", nil)
+       }()
        g.startPeriodicThread(func() {
                if err := g.SaveConfig(); err != nil {
                        log.Fatal(err)
```

and running `go run cmd/gomultiwa/main.go`

**Comment by fharding1** [comment]
@ski7777 respectfully, you've still not posted a runnable minimal reproduction of the issue you're reporting. This issue states "I'm trying to add a route after the server is already running." From my example, you can clearly see that it's possible to register a handler while the server is running. I would appreciate if you could post a more minimal example of the issue you're having, otherwise it's a lot of effort to audit your code base and try to figure out what's up. Thanks.

**Comment by ski7777** [comment]
Sadly I can´t provide better testing code but there is something I found out:
Running
```
	router.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
		t, err := route.GetPathTemplate()
		if err != nil {
			log.Println(err)
			return err
		}
		fmt.Println(t)
		return nil
	})
```
will print out all route names apart from the one registered later. There I get the following error:
`mux: route doesn't have a path`.

Just a reminder. This is the code for creating the route: `router.HandleFunc("/path", func(w http.ResponseWriter, r *http.Request) {}).Methods("GET")`

Regards
Raphael

**Comment by ski7777** [comment]
Any ideas?

**Comment by ski7777** [comment]
Just checked the code. There seems to be some problem in gorilla/mux. It seems like https://github.com/gorilla/mux/blob/ff4e71f144166b1dfe3017a146f8ed32a82e688b/route.go#L214 does not run. This causes `mux: route doesn't have a path`

**Comment by ski7777** [comment]
After ignoring this problem for a while I found the issue. It was a missing slash...
`ws.router.HandleFunc("abc", func(http.ResponseWriter, *http.Request){}).Methods("GET")` must be `ws.router.HandleFunc("/abc", func(http.ResponseWriter, *http.Request){}).Methods("GET")`
