### ISSUE TITLE
[feature] Use 308 redirect instead of 301 redirect for trailing slashes

### ISSUE THREAD

**Issue by krotscheck** [gorilla/mux#561]
HTTP 301 redirects - as per implementation convention in browsers - do not enforce that the HTTP Method should be retained when a client is moved to the new location. This is useful, in that a POST creation request can redirect to the newly generated resource as a GET. However, in situations where a POST request _itself_ needs to be redirected before it can be served, this is not useful.

In the case of `mux/regexp.go:353`, the trailing-slash redirect can cause the client to change the HTTP method from POST/PUT/DELETE to GET.

**Describe the solution you'd like**

https://tools.ietf.org/html/rfc7538 declares the 308 status code, which requires that the HTTP method be retained. For something that is basically just a path rewrite, using this status code seems more appropriate (aka `StatusPermanentRedirect`), as we cannot make assumptions about the downstream implementation.

>What would the feature look like? How would it work? How would it change the API?

Instead of returning a 301, it would return a 308

**Describe alternatives you've considered**

Alternatives mostly mean implementing a special case downstream, circumventing this code altogether.

**Comment by elithrar** [comment]
There are a few cases where we have discussed changing this, but have
considered it part of the public API.

The workaround is to use middleware, or possibly an option on the Router,
to change it.

(There are examples of this middleware - am commuting so can’t link
easily!)

**Comment by krotscheck** [comment]
Well, yes; by strict definition this'd be a breaking change. The real question that needs to be answered first is "Is this a bug or not". If it is, and requires workarounds, then it should either be fixed in the next major release (as a breaking change), or released sooner with a configuration flag.

Personally, I think it's a bug, and should be fixed, however I don't have a strong opinion on the 'how'.

**Comment by maoueh** [comment]
I presume however that lots of client libraries (vs browsers) needs to be adapted to handle 308. `node-fetch` for example does not handle this yet, maybe even Golang HTTP client does not (I did not check).

I've been hit two or three times by this and each time, it's really hard to nail the problem, because libraries often concatenate an endpoint with a path, and while doing a `GET` works, doing a `POST` (or any other verb) seems to work depending on the backend service but does not.

> Personally, I think it's a bug, and should be fixed

Agreed. An option allowing to choose the redirect code or custom handler would be good IMO here. This way some could send a 307 which is well handled currently while not permanent, others 308 and others something else.

**Comment by elithrar** [comment]
The best way to resolve this per-application is to write middleware that rewrites 301/302 to 308/307 for your application as appropriate.

I think it’s a stretch to call this a bug as it’s valid HTTP behavior - and more compatible.
