### ISSUE TITLE
HTTP Methods Should Be Constants

### ISSUE THREAD

**Issue by iamgroooooooot** [gorilla/mux#572]
At the moment Methods take string ie `"POST"` but I think it is better suited as constant provided by the package.

There might be a reason behind the current implementation and the method should being a constant might be more of a personal opinion.

Also this change might be a major version bump. 

Thoughts?

**Comment by fharding1** [comment]
While the HTTP standard defines a set of common methods, it's valid for an HTTP header to be any arbitrary string. For the same reason, the HTTP constants in `net/http` are strings, not a custom type/enum. I don't think any change is necessary since users can already use the standard library `net/http` string constants or any string they'd like.

**Comment by iamgroooooooot** [comment]
I also was suggesting strings constants and not enum. But since they are available in `net/http` it make sense to reuse them. Thanks @fharding1
