### ISSUE TITLE
[bug] HandleFunc routes all similar looking URLs to first registered url/handler

### ISSUE THREAD

**Issue by singhnarenn** [gorilla/mux#593]
**Describe the bug**
I've registered two similar URLs to different handler. But router ignores rest but first one and assumes these URLs to be same and calls the handler, which is registered first, while it should call the the handler registered with exact match of URL
…

**Versions**
```
$ go version
go version go1.14.4 darwin/amd64
```
…

**Steps to Reproduce**
Register below routes in given order:
v1.HandleFunc("**/attractions/{attractionID}**", gateway.HandleWithLogin(api.AttractionDetail).Methods(http.MethodGet)
v1.HandleFunc("/attractions/categories", gateway.HandleWithLogin(api.GetAttractionsCategories)).Methods(http.MethodGet)

`gateway.HandleWithLogin` internally parses the path and query params
Start the server and hit the second registered endpoint, error below is produced while calling the standard lib func `request.ParseForm()`:
```
2020/09/09 15:45:18 middleware.go:130: req.Form:map[attractionID:[categories]], req.PostForm:map[]
2020/09/09 15:45:18 middleware_helper.go:92: failed to parse path value=`categories` to int
2020/09/09 15:45:18 middleware.go:133: parsing url failed, err=failed to parse path value=`categories` to int
```
Make note of req.Form content above

…

**Expected behavior**
Both URLs registered should invoke respective handlers.

…

**Code Snippets**
Route registeration:

v1.HandleFunc(**_"/attractions/{attractionID}"_**, gateway.HandleWithLogin(api.AttractionDetail).Methods(http.MethodGet)
v1.HandleFunc(_**"/attractions/categories"**_,gateway.HandleWithLogin(api.GetAttractionsCategories)).Methods(http.MethodGet)

snippet from middleware:
```
		log.Printf("req.Form:%+v, req.PostForm:%+v\n", request.Form, request.PostForm)
		errParse := fillPathVarsToDto(dtoNew, request.Form)
		if errParse != nil {
			log.Printf("parsing url failed, err=%+v", errParse)
			writer.WriteHeader(http.StatusBadRequest)
			resp, _ := json.Marshal(&APIError{Msg: fmt.Sprintf("%s", errParse)})
			writer.Write(resp)
			return
		}
```
`fillPathVarsToDto` fills the parsed form data to req dto
…

**Comment by rastann** [comment]
yes, it happens to me also the same scenario.

**Comment by naren8** [comment]
No, i didn't. Just using different URL for now `/attractions/categories` -> `/attraction/categories` till i find something better.

**Comment by mrngm** [comment]
This behaviour is actually documented in the README, clarified in [#297](https://github.com/gorilla/mux/pull/297/files) in 2017.

Your bug description clearly states the problem you have: you try to match _two similar_ routes. However, the first route you add contains a very generic placeholder. Without constraints, this placeholder can match practically _anything_, **including** the word `categories`.

When `mux` iterates (in order!) the routes you have defined, and tries to match the request with each route, the first one will match, because it has the most generic form, comparable to: `/attractions/*`, where `*` indicates a wildcard.

Your solution would be to make sure the most-specific routes are added first, before adding the more generic routes. Another option is to restrict the `attractionID` placeholder, as you've already mentioned [here](https://github.com/gorilla/mux/issues/593#issuecomment-699520325). As a bonus: you can keep the order of the routes as you originally posted, because `/attractions/{attractionID:[0-9]+}` will never match the word `categories`.
