### ISSUE TITLE
Mux package

### ISSUE THREAD

**Issue by Montana** [gorilla/mux#611]
I'm using Gorilla mux as my router and dispatcher in my Golang apps and I have a relatively simple question, that I'm just missing.

In my main, I create a router: `r := mux.NewRouter()`. A few lines further, I register a handler: `r.HandleFunc("/", doSomething)`.

Works fine, but now my problem is that I have a package which adds handlers to the http package of Golang and not to my mux router. Like this:

```go
func AddInternalHandlers() {
    http.HandleFunc("/internal/selfdiagnose.html", handleSelfdiagnose)
    http.HandleFunc("/internal/selfdiagnose.xml", handleSelfdiagnose)
    http.HandleFunc("/internal/selfdiagnose.json", handleSelfdiagnose)
}
```
As you can see, it adds handles to the `http.HandleFunc` and not to the `mux-handleFunc`. Any idea how I can fix this without touching the package itself?

I'm aware the developer/author of selfdiagnose has the handlers public, so I used them directly to get:

```go

package main

import (
	"io"
	"log"

	"net/http"

	selfdiagnose "github.com/emicklei/go-selfdiagnose"
	"github.com/gorilla/mux"
)

func homeHandler(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, "home")
}

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/", homeHandler)
	r.HandleFunc("/debug", selfdiagnose.HandleSelfdiagnose)

	selfdiagnose.AddInternalHandlers()

	err := http.ListenAndServe(":8080", r)
	if err != nil {
		log.Println(err)
	}

}
```
Still no luck though, any ideas? Would be amazing. Love Gorilla and what you folks are doing.

-Montana Mendy

**Comment by andrewpillar** [comment]
You shouldn't need to call `selfdiagnose.AddInternalHandlers` as this will only add handlers against the `DefaultServeMux` in `net/http`. You've already got a handler setup for `HandleSelfdiagnose` so that should work fine. Looking at the implementation of `Handleselfdiagnose` from the package it checks the suffix of the requested URL path to determine the content type to send back (XML, JSON, or HTML). So you would need to configure the different routes for this like so,

```
r.HandleFunc("debug.json", selfdiagnose.HandleSelfdiagnose)
r.HandleFunc("debug.xml", selfdiagnose.HandleSelfdiagnose)
```

You can see the implementation of `HandleSelfdiagnose` here [1]. For what it's worth I ran your code and it appears to work as expected when you request the `/debug` endpoint.

[1] - https://github.com/emicklei/go-selfdiagnose/blob/master/handlers.go#L27

**Comment by Montana** [comment]
Thank you @andrewpillar!
