### ISSUE TITLE
[question] Behavior of http.ServeMux versus mux.Router

### ISSUE THREAD

**Issue by amitsaha** [gorilla/mux#616]
**Describe the problem you're having**

Consider the following handler function registrations with `mux.Router`:

```
r.HandleFunc("/", defaultHandler)
r.HandleFunc("/api/package", packageGetHandler).Methods("GET")
```

And with the ServeMux object:

```
mux.HandleFunc("/", defaultHandler)
mux.HandleFunc("/api/package", packageGetHandler)
```

For the first case, requests to `/foo` will get a 404, while for the second case, it will be handled by the `defaultHandler`.
Is this essentially an intentionally explicit behavior in `mux`? 

**Versions**

Go: 1.15.6 darwin/amd64
Package version: 1.8.0

**Comment by msiner** [comment]
I would say that this is a consequence of the intentional design decision to add extra functionality to the Handle and HandleFunc functions. That is, mux implementations of those functions are already not compatible with net/http due to the expanded and incompatible pattern syntax. However, I believe it is still possible to implement the behavior you were expecting using something like the following code.
```go
r.HandleFunc("/api/package", packageGetHandler).Methods("GET")
// The default handler must be added last.
r.PathPrefix("/").HandlerFunc(defaultHandler)
```
