### ISSUE TITLE
[bug] 301 redirect changes HTTP method from PUT to GET

### ISSUE THREAD

**Issue by sm4ll-3gg** [gorilla/mux#626]
**Describe the bug**

When mux receives a request it tries to clean the request path and, if the cleaned path differs from the original one, it does 301 redirect to the new one.
This type of redirect sometimes leads to the changing HTTP method to GET despite that the standard says that the method and body shouldn't be altered.
I faced that PUT request is changed to the GET during redirect. 

MDN says that 301 should be used only with GET and HEAD methods, while 308 is intended for POST.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

What do you think of doing a redirect with 308 instead of 301 for not GET, HEAD methods? https://github.com/gorilla/mux/blob/d07530f46e1eec4e40346e24af34dcc6750ad39f/mux.go#L190

**Versions**
> Go version: `go version`

go1.16.2 darwin/amd64

> package version: run `git rev-parse HEAD` inside the repo

d07530f46e1eec4e40346e24af34dcc6750ad39f (latest for now)

**Steps to Reproduce**
> How can the bug be triggered?

Just run a test below)

**Expected behavior**
> What output or behaviour were you expecting instead?

Passed test expected (the request is redirected to the cleaned path with the same HTTP method)

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

```go
func TestCleanPathRedirect_HTTPMethodChange(t *testing.T) {
	getHandler := func(w http.ResponseWriter, r *http.Request) {
		t.Error("unexpected switch method to GET")
		w.WriteHeader(http.StatusOK)
	}

	putCalled := false
	putHandler := func(w http.ResponseWriter, r *http.Request) {
		putCalled = true
		w.WriteHeader(http.StatusOK)
	}

	r := NewRouter()
	sub := r.PathPrefix("/some/path/").Subrouter()
	sub.HandleFunc("/", getHandler).Methods(http.MethodGet)
	sub.HandleFunc("/", putHandler).Methods(http.MethodPut)

	server := httptest.NewServer(r)
	defer server.Close()

	target, err := url.Parse(server.URL)
	if err != nil {
		t.Fatalf("url parsing failed: %v", err)
	}
	target.Path = "/some/path//" // will be cleaned to /some/path/

	req, err := http.NewRequest(http.MethodPut, target.String(), nil)
	if err != nil {
		t.Fatalf("request creation failed: %v", err)
	}

	resp, err := server.Client().Do(req)
	if err != nil {
		t.Fatalf("http request failed: %v", err)
	}

	if resp.StatusCode != http.StatusOK {
		t.Errorf("unexpected status code: %d", resp.StatusCode)
	}
	if !putCalled {
		t.Error("PUT handler haven't been called")
	}
}
```

**Comment by maoueh** [comment]
Duplicate of https://github.com/gorilla/mux/issues/561

**Comment by sm4ll-3gg** [comment]
> Mostly similar to #561

Yeah, it is. I didn't find it, sorry.
I've read the discussion there and I still don't think that this is valid behavior. 

> Note: For historical reasons, a user agent MAY change the request
> method from POST to GET for the subsequent request.  If this
> behavior is undesired, the 307 (Temporary Redirect) status code
> can be used instead.
> (c) https://datatracker.ietf.org/doc/html/rfc7231#section-6.4.2

This is really strange behaviour. Sending `PUT /do/some/action//` I receive result of the `GET /do/some/action/` because of automatic redirect handling on the server side. It can cause problems on the client side because it receive an undexpected response and don't aware of redirects under the hood. The client don't even have a `Location` header in the response. So, there is no way to determine if the URL is incorrect on the client side.

Provided that Go http implementation handles 308 correctly and redirects are handled automatically, it seems that redirecting with 308 instead of 301 (for methods other than GET and HEAD) won't be backward incompatible, will it?

**Comment by maoueh** [comment]
I totally agree with you by the way, I've been hit myself with a nasty sequence of event where the user was entering the URL with a trailing slash in an application code using a library. The library was then performing a POST, but since the user had a trailing slash in the URL, this performed a redirect and by return the 301 instead of 308, the library respected the "spec" so issued a GET after the redirect which leads to weirdo errors after that.

I'm also by the opinion that respecting the spec should be seen as a bug fix but I understand the opposite side where actual users could updated and have some breakage maybe because they are handling it specially.

All in all, an easier way to override the behavior at the router level feels to me like a good backward compatible compromise until a major version is expected.

**Comment by a-hennig** [comment]
I have encountered a related problem.  
My mux runs behind a reverse proxy that changes the prefix of the url, which the redirect swallows up.
- client browser calls https://my.com/box1/config, 
- should be redirected to https://my.com/box1/config/ via strictslash(true) 
- and from there to https://my.com/box1/config/index.html (my code).   

it works fine in a non-proxy setup (https://my.box1.com/config), and the second redirect also with proxy, because nginx is so kind to provide "X-Forwarded-Prefix" as a header and I use that to concatenate the real (host-relative) address.  
Since "X-Forwarded-Prefix" is not standardized, I consider this a "heuristic" and will face my surprises with other proxies.  
But I would need to apply that heuristics also to the strict-slash redirect in https://github.com/gorilla/mux/blob/v1.8.0/regexp.go#359.  

So I wonder, if the solution to this issue and my problem could be making the redirector an "configurable handler"  like NotFoundHandler and MethodNotAllowedHandler of the mux router.
