### ISSUE TITLE
[question] Return map[string]int from Vars function

### ISSUE THREAD

**Issue by rubymongoose** [gorilla/mux#665]
**Describe the problem you're having**

Hello, how can I change Vars function (or create my) to return map[string]int instead of map[string]string?
[https://github.com/gorilla/mux/blob/91708ff8e35bafc8612f690a25f5dd0be6f16864/mux.go#L429-L435](https://github.com/gorilla/mux/blob/91708ff8e35bafc8612f690a25f5dd0be6f16864/mux.go#L429-L435)

**Versions**
> Go version: `1.15.6`

**Comment by DavidLarsKetch** [comment]
Hey @rubymongoose, I'm not sure I understand the question, but check out A Tour of Go to start on [declaring functions](https://go.dev/tour/basics/4) and [empty interfaces (`interface{}`) and type assertions](https://go.dev/tour/methods/15), they may give you better guidance.

**Comment by ArkjuniorK** [comment]
Hey @rubymongoose, about your question i think it would be more simple to convert the `string` to an `int` than creating new function that return `map[string]int` since it would be complicated I guess.

Here example of using `strconv` package
```go
import (
   "http"
   "strconv"

   "github.com/gorilla/mux"
)

func someFunction(w http.ResponseWriter, r *http.Request) {
   vars := mux.Vars(r)
   id, err := strconv.ParseInt(vars["id"], 10, 64)
   if err != nil {
      http.Error(w, "Unable to convert string to int", http.StatusInternalServerError)
      return
   }
  
  // ... rest of the code
}

```

You could read more about `strconv` package [here](https://pkg.go.dev/strconv#ParseInt).

**Comment by rubymongoose** [comment]
@ArkjuniorK thank you for help :) I'll try it soon
