### ISSUE TITLE
Route.URL creates incorrect URL when PathPrefix is in use

### ISSUE THREAD

**Issue by endophage** [gorilla/mux#86]
Maybe I'm misunderstanding but if I have a Route with a defined path prefix, on making use of Route.URL the prefix is appended, rather than prepended. Sample code:

```go
package main

import (
    "fmt"
    "github.com/gorilla/mux"
)

func main() {
    r := mux.NewRouter()
    route := r.Path("/testpath").PathPrefix("/prefix/")
    url, _ := route.URL()
    fmt.Println(url)
}
```

The Println outputs /testpath/prefix/

**Comment by eastwood** [comment]
I believe this is correct behavior. Though I can understand the confusion. The `PathPrefix` doesn't prefix all the set `Path` routes per se, but in fact behaves just like `Path` does. However, with the exception that it matches any path appended to the value. That may be a little verbose so, a little explanation! 

In the source, the `Route` type uses `Matchers` to determine whether a request is matching a given `Handler`. Think of a matcher like a regular expression and the route your creating is in essence, building up a regular expression.

In your code, the first statement:
``` 
r.Path( "/testpath")
```
You've essentially create a route that matches on specifically `/testpath`. Continuing on...
```
r.Path("/testpath").PathPrefix("/prefix/")
```
When you add another matcher to the stack (it's sequential), it's says to match the criteria of `/prefix/.*` after you've matched "/testpath". Therefore, you've essentially created a route that says match any request with the Matcher (or regex):
`/testpath/prefix/.*` 

In lieu, think of the `PathPrefix` Matcher, just like `Path` in that it chains `Matchers`. However, instead of matching strictly on the path given, it matches on anything beginning with the path given.

**Comment by endophage** [comment]
Yeah, I worked it out eventually. PathPrefix seems like a generally poorly named and probably redundant function IMO. If a developer knows only one regex, it's probably `.*`
